make compatible with template

diff --git a/rngdoc2 b/rngdoc2
--- a/rngdoc2
+++ b/rngdoc2
@@ -1,65 +1,52 @@
 #! /usr/bin/env bash
-JAVA=${JAVA:-java}
-_scriptdir=`dirname $0`
+myapp=myapp
+myname=$(echo $0 | sed 's|.*/||')
+mydir=$(dirname $0 | sed 's|/$||')
 
-usage() {
-  _j=${JAR:-$(findJarFile)}
-  if [ -z "$_j" ]; then
-      echo "Couldn't find the rngdoc2 jar file. Specify using the '-JAR {path-to-jar-file}' command line option."
-   else
-      $JAVA -jar $_j --help
-      cat <<EOF
-Additional args include
- -JAR {path-to-rngdoc2-jarfile} specify which rngdoc2 jar file to use
- -v, --verbose          wrapper script verbose output
- -Dlog4j.configurationFile={path-to-log4j2-config-file} 
-EOF
-  fi
+function usage() {
+    cat <<- xxx
+	Usage: $myname [+h] [+v] [+noop] <application-args>
+
+	Runs the $myapp application.
+
+	+h - print this message and stop. To see the application's
+	     help message use '-h'.
+	+v - print the java command before invocation.
+	+noop - don't actually invoke the java command.
+
+	These environment variables are used to alter behavior:
+	JAVA - identifies the java command
+	MYAPPJAR - identifies the jar file
+	xxx
+    exit
 }
 
-findJarFile() {
-  for d in . ./target ../../../maven-targets/model-compiler $_scriptdir; do
-    for x in $d/rngdoc2-*-jar-with-dependencies.jar $d/rngdoc2*.jar; do
-      if [ -f $x ]; then
-        echo $x
-        return
-      fi
-    done
-  done
-  return
-}
+function findJarFile() for c in ./$myapp*.jar $mydir/$myapp*.jar target/$myapp-*-with-dependencies.jar; do
+                         [ -r $c ] && echo $c
+                       done
+[ -z "$MYAPPJAR" ] && MYAPPJAR=$(findJarFile)
 
-argv=()
+verbose=
+noop=
 EXTRAJAVAARGS=()
 while [ -n "$1" ]; do
   case "$1" in
-    -h | --help)
-            usage
-            exit 1
-            ;;
-    -JAR)
-            JAR=$1
-            shift
-            ;;
-    -v | --verbose)
-            verbose=verbose
-            ;;
-    -D*)
-            EXTRAJAVAARGS+=$1
-            ;;
-    *)
-            argv+=($1)
-            ;;
+    +h) usage
+	;;
+    +v) verbose=verbose
+	;;
+    +noop) noop=noop
+	;;
+    *)  break
   esac
   shift
 done
 
-[ -n "$JAR" ] || JAR=`findJarFile`
-if [ -z "$JAR" ]; then
-  echo "Couldn't find the rngdoc2 jar file. Specify using the '-JAR {path-to-jar-file}' command line option." >&2
-  exit 1
+if [ -r "$MYAPPJAR" ]; then
+  echo "Couldn't find the rngdoc2 jar file!"
+  usage
 fi
 
-_cmd=$(echo $JAVA ${EXTRAJAVAARGS[@]} -jar $JAR ${argv[@]})
-[ -n "$verbose" ] && echo $_cmd
-$_cmd
+cmd="$JAVA -jar $MYAPPJAR $*"
+[ -z "$verbose" ] || echo $cmd
+[ -z "$noop" ] && exec $cmd
